# NUMPY

NumPy is a Python package. It stands for 'Numerical Python'. 
It is a library consisting of multidimensional array objects and a collection of routines for processing of array.  


# NumPy – An alternative for MatLab 

NumPy is often used along with packages like SciPy (Scientific Python) and Mat−plotlib (plotting library). This combination is widely used as a replacement for MatLab, a popular platform for technical computing. However, Python alternative to MatLab is now seen as a more modern and complete programming language. 

## Installation Instructions

**It is highly recommended you install Python using the Anaconda distribution to make sure all underlying dependencies (such as Linear Algebra libraries) all sync up with the use of a conda install. If you have Anaconda, install NumPy by going to your terminal or command prompt and typing:**
    
    conda install numpy
    
**If you do not have Anaconda and can not install it, please refer to [Numpy's official documentation on various installation instructions.](http://docs.scipy.org/doc/numpy-1.10.1/user/install.html)**

## Using NumPy

Once you've installed NumPy you can import it as a library:

In [1]:
import numpy as np # we import numpy as np,it's python covention to always import numpy as np



# Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [4]:
mylist = [1,2,3,4]

In [5]:
mylist

[1, 2, 3, 4]

In [8]:
np.array(mylist)

array([1, 2, 3, 4])

let's try creating matrix, a matrix is just a nested lists

In [9]:
matrix = [[1,2,3],[4,5,6],[6,7,8]]

In [10]:
np.array(matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

# NumPy − Array Attributes 
We will discuss the various array attributes of NumPy. 

## 1.ndarray.shape 
This array attribute returns a tuple consisting of array dimensions.

In [13]:
a=np.array([[1,2,3],[4,5,6]]) 

In [14]:
a.shape

(2, 3)

## 2. ndarray.ndim 
This array attribute returns the dimension of an array e.g 2D,3D
4D (if it exists)

In [17]:
b=np.array([[1,2,3],[4,5,6],[12,4,8]]) 
b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [12,  4,  8]])

In [19]:
b.ndim 

2

## 3. ndarray.dtype
It returns the data type of the values in a numpy array.
Note: numpy can only take values of thesame data type

In [21]:
b.dtype

dtype('int32')

# NumPy − Array Creation Routines 
A new ndarray object can be constructed by any of the following array creation routines 

### 1.arange ([sart,stop,step])

Return evenly spaced values within a given interval.

In [22]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

### 2. zeros and ones

Generate arrays of zeros or ones

In [24]:
np.zeros(3)

array([0., 0., 0.])

In [26]:
np.zeros((5,5)) # This creates zeros array of 5X5 shape

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [27]:
np.ones(3)

array([1., 1., 1.])

In [28]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### 3. linspace([start,end,num])
Return evenly spaced numbers over a specified interval.

In [31]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [32]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

### 4. numpy.logspace 
This function returns an ndarray object that contains the numbers that are evenly spaced on a log scale

In [33]:
np.logspace(1.0, 2.0, 2) 

array([ 10., 100.])

In [34]:
np.logspace(1.0, 10.0, 20) 

array([1.00000000e+01, 2.97635144e+01, 8.85866790e+01, 2.63665090e+02,
       7.84759970e+02, 2.33572147e+03, 6.95192796e+03, 2.06913808e+04,
       6.15848211e+04, 1.83298071e+05, 5.45559478e+05, 1.62377674e+06,
       4.83293024e+06, 1.43844989e+07, 4.28133240e+07, 1.27427499e+08,
       3.79269019e+08, 1.12883789e+09, 3.35981829e+09, 1.00000000e+10])

### 5. eye

Creates an identity matrix

In [35]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### 6. Random 

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [36]:
np.random.rand(2)

array([0.35372945, 0.79890634])

In [37]:
np.random.rand(5,5)

array([[0.57075896, 0.9434132 , 0.68123073, 0.68072282, 0.84307992],
       [0.12980563, 0.80139698, 0.05411707, 0.22510051, 0.59193759],
       [0.22796947, 0.53869283, 0.75065438, 0.87405654, 0.91147524],
       [0.81541568, 0.70391646, 0.85990126, 0.1104708 , 0.62975206],
       [0.79325301, 0.42595077, 0.6151086 , 0.43109695, 0.45823522]])

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [38]:
np.random.randn(2)

array([0.37153084, 1.19459423])

In [39]:
np.random.randn(5,5)

array([[ 1.19066634, -0.43029136,  0.49908394, -0.8945034 ,  0.27026546],
       [ 0.79219465, -0.45665214, -1.59060078,  0.54949613, -0.68429059],
       [-1.19769105,  0.2146238 ,  0.63376182, -0.39787132, -0.48066061],
       [-0.83309263, -0.66134734,  1.44849972,  1.18568718, -1.0217433 ],
       [-1.21334543,  0.60086425,  1.15535753,  1.34879155,  0.75679732]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [40]:
np.random.randint(1,100)

79

In [41]:
np.random.randint(1,100,10)

array([13, 76, 31, 56,  5, 41, 37, 87, 56, 65])

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [42]:
ranarr = np.array([10, 12, 41, 17, 49,  2, 46,  3, 19, 39])

In [43]:
ranarr.max()

49

In [44]:
ranarr.argmax()

4

In [45]:
ranarr.min()

2

In [46]:
ranarr.argmin()

5

# NumPy – Array Manipulation 
There are several ways of manipulation numpy array shape, we only discussed few here.

### 1.reshape 
Gives a new shape to an array without changing its data 

In [48]:
a = np.arange(8)
a

array([0, 1, 2, 3, 4, 5, 6, 7])

In [49]:
a.reshape(4,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

### 2. flatten 
This function returns a copy of an array collapsed into one dimension. The function takes the following parameters. 

In [54]:
a = np.arange(8).reshape(2,4) 
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [53]:
a.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7])

### 3.  numpy.ravel 
This function returns a flattened one-dimensional array.

In [56]:
a = np.arange(8).reshape(2,4) 
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [57]:
a.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7])

### 4.  numpy.ndarray.T 
This function belongs to ndarray class. It behaves similar to numpy.transpose. It return the transpose of an array

In [59]:
a = np.arange(12).reshape(3,4) 
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [60]:
a.T 

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

### 5. numpy.stack((arrqys),axis) 
This function joins the sequence of arrays along a new axis. This function has been added since NumPy version 1.10.0. Following parameters need to be provided. You will need this parameter alot when doing macine learning ensemble 

In [62]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [63]:
b = np.array([[5,6],[7,8]]) 
b

array([[5, 6],
       [7, 8]])

Stacking across row, axis=0.

In [64]:
np.stack((a,b),axis=0)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

Stacking across column

In [65]:
np.stack((a,b),axis=1)

array([[[1, 2],
        [5, 6]],

       [[3, 4],
        [7, 8]]])

There are many functions that won't be discussed in tis lecture,you have to read them up in the textbook i sent to the group.

# Great Job!